
# **1. Basic Array Manipulation:**


Create a 1D array with values ranging from 0 to 9.


In [7]:
import numpy as np

In [3]:
array_1D = np.arange(10)
print(array_1D)

[0 1 2 3 4 5 6 7 8 9]


Reshape the array into a 3x3 matrix.

Explore Reshape Function

In [10]:
for_matrix = np.arange(1,10)
print(for_matrix)

[1 2 3 4 5 6 7 8 9]


In [12]:
matrix = for_matrix.reshape(3,3)
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Access the element at the second row, second column.


In [15]:
matrix_array = np.array(matrix)
print(matrix_array)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
matrix[1,1]

5

In [17]:
matrix_array[1,1]

5

Perform element-wise addition, subtraction, multiplication, and division on two arrays [1, 2, 3] and [4, 5, 6].


In [22]:
array_A = np.array([1,2,3])
array_B = np.array([4,5,6])

In [28]:
addition_AB = array_A + array_B
print(addition_AB)
substract_AB = array_A - array_B
print(substract_AB)
multiply_AB = array_A * array_B
print(multiply_AB)
divide_AB = array_A / array_B
print(divide_AB)


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


Find the sum, mean, and standard deviation of the array [1, 2, 3, 4, 5].


In [29]:
array_D = [1, 2, 3, 4, 5]


In [32]:
np.sum(array_D)


15

In [33]:
np.mean(array_D)

3.0

In [34]:
np.std(array_D)

1.4142135623730951

Reshape the array [1, 2, 3, 4, 5, 6] into a 2x3 array.

Explore Reshape

In [36]:
reshape_array = np.array([1,2,3,4,5,6])
reshaped = reshape_array.reshape(2,3)
print(reshaped)

[[1 2 3]
 [4 5 6]]



# **2. Indexing and Slicing:**


Create a 5x5 array with random integers.


In [3]:
rand_int = np.random.randint(1,100,size=(5,5))
print(rand_int)

[[32 21 82 34 17]
 [12 42 27 76 11]
 [59 89 92 66  7]
 [ 2 40  3 82 72]
 [27 15 70 78 25]]


Replace all values in the sub-array with a specific value.


Extract the subarray [[3, 4], [7, 8]] from the array [[1, 2], [3, 4], [5, 6], [7, 8]].


In [17]:
an_array = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
subarray = an_array[(1,3),:]
print(subarray)

[[3 4]
 [7 8]]



# **3. Broadcasting:**

Create a 2D array of shape (3, 3) with values from 0 to 2.


In [19]:
array_2D = np.random.randint(0,2,size=(3,3))
print(array_2D)

[[0 1 0]
 [0 0 1]
 [1 0 1]]


Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.


In [21]:
array_1D = [3]
adding_arrays = array_2D + array_1D
print(adding_arrays)

[[3 4 3]
 [3 3 4]
 [4 3 4]]


# **4. Concatenation and Splitting**


1.   Create two 2D arrays of shape (3, 3) with random integers.
2.   Concatenate them horizontally and vertically.
3.   Split the concatenated arrays back into the original arrays.


In [23]:
array_one = np.random.randint(1,11,size=(3,3))
print(array_one)

[[ 8  5  1]
 [10  9  5]
 [ 3 10  3]]


In [24]:
array_two = np.random.randint(11,21,size=(3,3))
print(array_two)

[[14 20 11]
 [19 16 14]
 [19 17 16]]


In [31]:
print("Concatinate Horizontally")
concetinate = np.hstack((array_one,array_two))
print(concetinate)

Concetinate Horizontally
[[ 8  5  1 14 20 11]
 [10  9  5 19 16 14]
 [ 3 10  3 19 17 16]]


In [38]:
concatinate_vertical = np.vstack((array_one,array_two))
print(f'Concatinate Vertically:\n{concatinate_vertical}')

Concatinate Vertically:
[[ 8  5  1]
 [10  9  5]
 [ 3 10  3]
 [14 20 11]
 [19 16 14]
 [19 17 16]]


# **Bonus Question**

Find mode of this array  = [1,2,1,2,3,4,5,6,8,9,1,2,2,22,21,1,1,1,1,2,5]

Hint: Use count and also loop

In [4]:
arrayy = [1,2,1,2,3,4,5,6,8,9,1,2,2,22,21,1,1,1,1,2,5]

In [5]:
array_dict = {}

for temp in arrayy:
    if temp in array_dict:
        array_dict[temp] += 1
    else:
        array_dict[temp] = 1
        
mode = None
count = 0

for mode, count in array_dict.items():
    if count > count:
        mode = mode
        count = count
        
print(f'Mode of this array is {mode} and counts is {count}')

Mode of this array is 21 and counts is 1


# **Notes**


1.   All the Questions carry Equal Points (2 points)

2.   Bonus Question carry 5 points

3.   Review lecture for any query

Good Luck!

